server:
  port: 8080

spring:
  application:
    name: ocpp-csms

  datasource:
    url: jdbc:postgresql://localhost:5432/ocpp_csms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

logging:
  level:
    com.csms: DEBUG
    org.springframework.web.socket: DEBUG

ocpp:
  websocket:
    path: /ocpp/{chargePointId}
  heartbeat:
    timeout: 600 # seconds
  transaction:
    timeout: 86400 # 24 hours in seconds